// Hermes Grill menu data — German dish names with additive codes + EUR prices.
window.HERMES = {
  info: {
    name: "Hermes Grill",
    tagline: "Griechische Spezialitäten",
    owner: "Vasiliki Milona",
    address: ["Mannheimer Straße 42", "68309 Mannheim"],
    phone: "0621 / 734442",
    hours: [
      ["Mittwoch – Sonntag", "11:30 – 14:00 Uhr"],
      ["", "17:00 – 23:00 Uhr"],
      ["Warme Küche", "bis 22:00 Uhr"],
      ["Montag & Dienstag", "Ruhetag"],
    ],
    about:
      "Wenn Sie griechische Spezialitäten in gemütlicher Atmosphäre genießen möchten, sind Sie bei uns genau richtig! Bei uns erwartet Sie beste Qualität, eine entspannte Atmosphäre und freundliches Personal. Zusätzlich bieten wir ein schönes Nebenzimmer oder den separaten Anbau für größere oder kleinere Festlichkeiten an.",
    notice:
      "Wir wünschen Ihnen einen guten Rutsch ins neue Jahr 2026! Unser Restaurant bleibt vom 01.01. bis 06.01.2026 geschlossen. Ab dem 07.01. sind wir wie gewohnt für Sie da.",
  },
  additives: [
    ["1", "mit Farbstoff"],
    ["2", "mit Konservierungsstoff"],
    ["3", "mit Antioxidationsmittel"],
    ["4", "mit Geschmacksverstärker"],
    ["5", "geschwefelt"],
    ["6", "geschwärzt"],
    ["7", "gewachst"],
    ["8", "mit Süßungsmittel"],
    ["9", "enthält Phenylalaninquelle"],
    ["10", "mit Phosphat"],
    ["11", "coffeinhaltig"],
    ["12", "chininhaltig"],
  ],
  categories: [
    { id: "suppen", title: "Suppen", items: [
      { no: 121, n: "Spargelcremesuppe", a: "4", p: "5,80" },
      { no: 122, n: "Tomatensuppe mit Sahnehäubchen", p: "5,80" },
      { no: 123, n: "Pfeffersuppe", p: "5,80" },
      { no: 124, n: "Hühnersuppe", p: "5,80" },
    ]},
    { id: "warme-vorspeisen", title: "Warme Vorspeisen", items: [
      { no: 102, n: "Schafskäse in der Pfanne — mit Champignons, Paprika, Tomaten, Knoblauch", p: "9,50" },
      { no: 103, n: "Schafskäse paniert", p: "8,50" },
      { no: 104, n: "Schafskäse gegrillt", p: "8,80" },
      { no: 105, n: "Gegrillte Peperoni — mit Kräuterbutter & Knoblauch", a: "2,3", p: "7,90" },
      { no: 107, n: "Gigantes — weiße Bohnen mit Schafskäse überbacken", a: "3", p: "8,20" },
      { no: 108, n: "Champignons mit Käsefüllung", a: "1", p: "9,20" },
      { no: 126, n: "Gebackene Auberginen und Zucchini", p: "8,80" },
      { no: 127, n: "Pourakia gebacken (6 St.) — Blätterteigröllchen mit Tsatsiki", p: "8,20" },
      { no: 116, n: "Käsekroketten", a: "1", p: "7,80" },
    ]},
    { id: "thalassina", title: "Thalassina — Aus dem Meer", items: [
      { no: 111, n: "Calamaresringe paniert", a: "1,4", p: "10,50" },
      { no: 112, n: "Calamares natur gebacken", p: "14,50" },
      { no: 114, n: "Sardellen gebacken", p: "8,90" },
      { no: 113, n: "Riesengarnelen gegrillt (4 St.)", p: "14,80" },
      { no: 118, n: "Oktapodi „Salata\" — Oktopus in Öl & Essig mariniert", p: "18,50" },
      { no: 135, n: "Oktapodi „Stifado\" — Oktopus mit Perlzwiebeln, pikant", a: "4", p: "19,80" },
      { no: 106, n: "Garides „Skordates\" — Garnelen in scharfem Knoblauchöl", p: "15,80" },
    ]},
    { id: "kalte-vorspeisen", title: "Kalte Vorspeisen", items: [
      { no: 100, n: "Tsatsiki — Joghurt, Gurke, Knoblauch", p: "7,50" },
      { no: 109, n: "Dolmades — gefüllte Weinblätter", p: "7,80" },
      { no: 115, n: "Taramosalata — Fischrogencreme mit Olivenöl & Zitrone", a: "1", p: "7,80" },
      { no: 119, n: "Tirosalata — pürierter Schafskäse, würzig", a: "3", p: "7,80" },
      { no: 117, n: "Vorspeisenplatte (ab 2 Personen)", p: "12,00 p.P." },
    ]},
    { id: "salate", title: "Salate", items: [
      { no: 133, n: "Kleiner gemischter Salat", a: "2", p: "5,00" },
      { no: 139, n: "Griechischer Bauernsalat mit Schafskäse", a: "2", p: "9,50" },
      { no: 131, n: "Horiatiki — Schafskäse, Tomaten, Gurke, Zwiebeln", p: "8,50" },
      { no: 130, n: "Salat „Hermes\" — Garnelen, Oktopus, Champignons, Joghurtdressing", a: "3", p: "15,20" },
      { no: 129, n: "Salat „nach Art des Hauses\" — Putenstreifen & Champignons", a: "3", p: "13,80" },
      { no: 128, n: "Lammstreifen auf Blattsalat der Saison", a: "2", p: "15,50" },
      { no: 237, n: "Rinderfiletstreifen auf Blattsalat, Balsamico-Knoblauch", a: "2", p: "16,20" },
      { no: 138, n: "Salat „Poseidon\" — Riesengarnelen, Zucchini & Paprika", a: "2", p: "15,20" },
      { no: 137, n: "Feldsalat mit gerösteten Baconstreifen", a: "2", p: "8,40" },
    ]},
    { id: "frischfisch", title: "Frischfisch & Fischkarte", note: "Die frische Fischauswahl wird Ihnen wie in Griechenland üblich gezeigt.", items: [
      { no: 300, n: "Fischsuppe „mediterraner Art\" — mit Garnelen, Muscheln & mehr", p: "14,80" },
      { no: 302, n: "Cambas — 5 Riesengarnelen am Spieß mit Reis & Gemüse", p: "18,50" },
      { no: 305, n: "Dorade Royal — mit Reis & Gemüse", p: "21,50" },
      { no: 308, n: "Kabeljaufilet gebacken — mit mediterranem Gemüsereis", p: "24,50" },
      { no: 310, n: "Lachssteak gegrillt — in Sherry-Sahnesauce auf Tagliatelle", p: "21,50" },
      { no: 304, n: "Thunfisch gegrillt (auf Anfrage)", p: "32,50" },
    ]},
    { id: "lamm-grill", title: "Vom Lamm — Vom Grill", note: "Nur neuseeländisches Weidelamm. Mit griechischen Ofenkartoffeln, grünen Bohnen & Salat.", items: [
      { no: 146, n: "Lammkoteletts (Lammkrone)", p: "32,50" },
      { no: 145, n: "Lammfilet am Spieß", p: "32,50" },
      { no: 147, n: "Zarte Lammhüfte mit Schafskäse", p: "29,50" },
      { no: 250, n: "Lamm Platte — Koteletts, Filet & Rückensteak", p: "32,50" },
    ]},
    { id: "lamm-ofen", title: "Vom Lamm — Aus dem Backofen", note: "Arni = Junglamm, Fournos = Ofen. Mit marktfrischem Salat.", items: [
      { no: 152, n: "Arni sto Fourno me Patates — mit Zitronenkartoffeln", p: "23,50" },
      { no: 153, n: "Arni sto Fourno me Kritharaki — mit Reisnudeln", p: "23,50" },
      { no: 155, n: "Arni sto Fourno me Fasolakia — mit grünen Bohnen", p: "23,50" },
      { no: 156, n: "Arni sto Fourno me Gigantes — mit Riesenbohnen", a: "3", p: "23,50" },
      { no: 157, n: "Ganze Lammkeule (ab 4 Personen, Vorbestellung)", p: "27,20 p.P." },
    ]},
    { id: "rind", title: "Vom Rind", note: "Nur frisches Angus-Rinderfilet. Steaks ab 290 g, medium gegrillt.", items: [
      { no: 163, n: "Ochsenspieß", p: "30,50" },
      { no: 161, n: "Knoblauchspieß — mit frischem Knoblauch", p: "31,00" },
      { no: 162, n: "Rinderfilet am Spieß", p: "31,50" },
      { no: 193, n: "Rinderfilet am Spieß — mit Paprika & Zwiebeln", p: "32,50" },
      { no: 178, n: "Zwei Filetsteaks — in feiner Metaxasauce", p: "38,00" },
      { no: 179, n: "Filetsteak — mit frischen Champignons", p: "38,50" },
      { no: 180, n: "Filetsteak", p: "37,00" },
      { no: 181, n: "Knoblauchsteak", p: "38,50" },
      { no: 182, n: "Pfeffersteak — in Madagaskar-Pfeffersauce", p: "38,50" },
      { no: 183, n: "Rumpsteak — mit Zwiebeln oder Kräuterbutter", p: "32,50" },
      { no: 272, n: "Kalbskotelett", p: "32,50" },
    ]},
    { id: "schwein", title: "Grillspezialitäten — Vom Schwein", items: [
      { no: 140, n: "Spieß und zwei Suzukakia", a: "2", p: "12,50" },
      { no: 141, n: "Spießbraten", a: "2", p: "12,50" },
      { no: 142, n: "Suzukakia", a: "2", p: "17,20" },
      { no: 143, n: "Bauernhacksteak — gefüllt mit Schafskäse", a: "2", p: "18,80" },
      { no: 159, n: "Mixgrill", a: "2", p: "17,50" },
      { no: 167, n: "Mixgrill mit Käse überbacken", a: "1,2", p: "18,50" },
      { no: 160, n: "Teufelsspieß — mit scharfer Sauce", a: "2,3", p: "19,40" },
      { no: 164, n: "Hermesspieß — mit Peperoni & Zwiebeln", a: "2,3", p: "18,50" },
    ]},
    { id: "gyros", title: "Gyros", note: "Mittwoch, Freitag, Samstag & Sonntag ab 17:00 Uhr.", items: [
      { no: 144, n: "Gyros vom Drehspieß — mit Tomaten, Zwiebeln, Tsatsiki", a: "2", p: "17,50" },
      { no: 158, n: "Gyros mit Metaxasauce", a: "1,2", p: "18,80" },
      { no: 190, n: "Gyros Spezial — mit Metaxasauce & Käse überbacken", a: "1,2", p: "20,50" },
    ]},
    { id: "lenden", title: "Lendenspieße & Schweinefilet", items: [
      { no: 165, n: "Lendenspieß", a: "2", p: "21,50" },
      { no: 166, n: "Lendenspieß — mit Käse überbacken", a: "1,2", p: "22,50" },
      { no: 168, n: "Fetaspieß — Lendenmedaillons mit Schafskäse", a: "2", p: "22,50" },
      { no: 185, n: "Bauernspieß — mit Tomaten, Paprika, Zwiebeln", a: "2", p: "21,50" },
      { no: 169, n: "Manitarispieß — mit gefüllten Champignons", a: "1,2", p: "22,50" },
      { no: 191, n: "Schweinefiletpfännchen — in Metaxasauce", a: "1,2", p: "22,80" },
      { no: 189, n: "Lendensteak „nach Balkan Art\" — in Rahmsauce", a: "2", p: "22,50" },
    ]},
    { id: "gefluegel", title: "Geflügel", items: [
      { no: 194, n: "Putenspieß — mit Paprika, Zwiebeln, Käse überbacken", a: "1,2", p: "17,80" },
      { no: 195, n: "Putensteak", a: "2", p: "17,20" },
      { no: 198, n: "Putensteak — mit Champignons in Rieslingsauce & Rösti", a: "2", p: "18,80" },
    ]},
    { id: "platten", title: "Platten", note: "Mit Beilagen & gemischtem Salat. Auch für mehrere Personen.", items: [
      { no: 170, n: "Theo Platte — Spieß, Steak & kleines Hacksteak", a: "2", p: "19,50" },
      { no: 171, n: "Spezial Platte — Lammlende, Schweinelende, Filetsteak & Lammkotelett", a: "2", p: "33,50" },
      { no: 173, n: "Parga Platte — Spieß, Steak & zwei Suzukakia", a: "2", p: "20,80" },
      { no: 174, n: "Gyros Platte — Gyros & kleines Hacksteak", a: "2", p: "18,50" },
      { no: 175, n: "Bauern Platte — Spieß, Steak, Lammkotelett, Suzukakia & Feta", a: "2", p: "23,50" },
    ]},
    { id: "vegetarisch", title: "Vegetarisch", items: [
      { no: 192, n: "Vegetarischer Spieß — Tomaten, Paprika, Zwiebeln, Champignons & Feta", a: "2", p: "17,20" },
      { no: 151, n: "Mousaka — Auflauf mit Auberginen, Hackfleisch & Béchamel", a: "1,2", p: "18,50" },
    ]},
    { id: "deutsch", title: "Aus der deutschen Küche", items: [
      { no: 188, n: "Schnitzel paniert", p: "16,50" },
      { no: 186, n: "Jägerschnitzel", p: "17,80" },
      { no: 260, n: "Putenschnitzel", p: "17,20" },
    ]},
    { id: "kinder", title: "Für unsere kleinen Gäste", note: "Mit Pommes & kleinem Salat. Malblock & Stifte vorhanden.", items: [
      { no: 80, n: "Zarter Lendenspieß — mit Käse überbacken", a: "1", p: "10,80" },
      { no: 81, n: "Kleines paniertes Schnitzel", p: "9,50" },
      { no: 82, n: "Mini Mix", p: "9,50" },
      { no: 83, n: "Kleines paniertes Putenschnitzel", p: "9,50" },
      { no: 99, n: "Kleines Lachssteak", p: "12,80" },
    ]},
    { id: "beilagen", title: "Beilagen", items: [
      { no: 84, n: "Geröstetes Knoblauchbrot", p: "3,00" },
      { no: 85, n: "Pommes frites", p: "3,50" },
      { no: 87, n: "Griechische Kartoffeln aus dem Backofen", p: "3,50" },
      { no: 88, n: "Kroketten", p: "3,50" },
      { no: 89, n: "Djuwetschreis", p: "3,50" },
    ]},
    { id: "dessert", title: "Dessert", items: [
      { no: 90, n: "Dimi Becher — gemischtes Eis mit Eierlikör", a: "1", p: "7,50" },
      { no: 92, n: "Gemischtes Eis mit Sahne", a: "1", p: "6,50" },
      { no: 93, n: "Vanilleeis mit flambierten Himbeeren", a: "1", p: "7,50" },
      { no: 94, n: "Vanilleeis mit heißer Schokoladensauce", a: "1", p: "7,50" },
      { no: 96, n: "Griechischer Sahnejoghurt mit Honig & Walnüssen", p: "7,50" },
      { no: 97, n: "Griechischer Sahnejoghurt mit frischem Obst", p: "9,50" },
      { no: 91, n: "Kataifi — Süßgebäck mit Vanilleeis & Walnüssen", a: "1", p: "8,50" },
      { no: 98, n: "Pagoto — gemischtes Eis mit frischem Obst", a: "1", p: "9,50" },
    ]},
  ],
};
